// ---------------------------------------------------------------------------
// Stub for convex/_generated/api.ts
//
// This file is normally auto-generated by `npx convex dev`. This stub exists
// so the project builds before the Convex CLI has been run. Once you run
// `npx convex dev`, this file will be overwritten with the real generated code.
// ---------------------------------------------------------------------------

/* eslint-disable @typescript-eslint/no-explicit-any */

const stub = new Proxy(
  {},
  {
    get(_target, _prop) {
      return new Proxy(
        {},
        {
          get(_t, _p) {
            // Returns a placeholder that useConvexQuery/useConvexMutation will
            // accept as a FunctionReference. At runtime, the Convex client
            // won't be initialised (no VITE_CONVEX_URL) so these are never
            // actually sent to the server.
            return `stub` as any;
          },
        },
      );
    },
  },
) as any;

export const api = stub;
export const internal = stub;
